version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: bancario-auth-db
    environment:
      POSTGRES_PASSWORD: SystemBank0101@reza
      POSTGRES_DB: BankAuthDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: